server:
  host: "localhost"
  port: 1883
  topic: "tst/msg"
  user: "test"
  pass: "test1234"
generation:
  frequency: 10
  size:
    distribution: "normal"
    parA: 164
    parB: 4.8368
loglevel: "Warn"
